

# App configurations
app:
  host: "localhost"
  port: "5000"
  gin_mode: "debug"
  local: True

# Database credentials
database:
  db_dsn: "postgresql://gorm:secret@localhost:5432/godb?sslmode=disable"
