

# App configurations
app:
  host: "localhost"
  port: "5000"
  gin_mode: "debug"

# Database credentials
database:
  db_host: "localhost"
  db_user: "gorm"
  db_password: "secret"
  db_port: "5432"
  db_name: "gorm"
